# Generated by Django 4.2.4 on 2023-11-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.PositiveIntegerField(blank=True, default=1, unique=True, verbose_name='Участок'),
        ),
    ]
