# Generated by Django 4.2.4 on 2023-11-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_district_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, unique=True, verbose_name='Участок'),
        ),
    ]
