# Generated by Django 4.2.4 on 2023-12-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Участок', 'verbose_name_plural': 'Участки'},
        ),
    ]
